### ISSUE TITLE
Some Fibaro Door/Window sensors not shown anymore

### ISSUE THREAD

**Issue by klaasjoerg** [SphtKr/homebridge-zway#78] opened 2016-12-25 11:37 UTC
Is there a known, typical reason, that some (but not all) Fibaro Door/Window Sensors are not shown and initialized by homebridge-zway anymore?
Just noticed that some of them simply not appear in Homekit anymore. When doing a DEBUG they also are not listed during initialization while others do appear. Strange....

**Comment by SphtKr** [comment] 2017-01-03 06:10
Looks like a duplicate of #69

**Closed by SphtKr** 2017-01-03 06:10 UTC
Labels: duplicate
