### ISSUE TITLE
Problem with control of some accessories

### ISSUE THREAD

**Issue by devbox** [SphtKr/homebridge-zway#13] opened 2016-02-07 22:58 UTC
Hi,

here is my environment:
Z-Wave Controller:
Raspberry Pi 2
razberry Controller
z-way server 2.2.1 rc6

HomeKit Bridge:
Raspberry Pi 2
Homebridge
homekit-zway-plugin

HomeKitBridge zway-plugin connected to z-wave controller successfully.
iPhone HomeKit App paired successfully to HomeKitBridge and all accessories are shown.

z-way server has some accessories included:
Figaro Wall-Plug
Figaro Roller Shutter
Figaro Dimmer
Each accessory can be controlled correctly from the z-way UI. 

But the problem is, the only accessory which i can control with iOS HomeKit App is the Fibaro Wall-Plug.
The Dimmer and Roller Shutter only shows the actually state, but when trying to change value, it doesn´t change.

What can i do? Which information do you exactly need for help? (did´t know what exactly is meant in readme.)

**Comment by SphtKr** [comment] 2016-02-08 05:51
Hello,

I need a copy of your `devices` output. You'll need to login to the Z-Way standard UI--e.g. at `http://your.pi.i.p:8083/`, and then from that same browser window hit `http://your.pi.i.p:8083/ZAutomation/api/v1/devices` (replacing your.pi.i.p with your device's IP address of course), and attach or post the contents here.

Funny, the dimmer definitely should have worked, but I have no roller shutters, so I probably need to make some changes to get that to work.

**Comment by devbox** [comment] 2016-02-08 10:57
Thanks!
So, here I attached the devices.
1.Fibar Group Switch 2-0 -> works (Fibar Wall-Plug)
2.Switch 3-0 Everspring -> not working (Fibar Roller Shutter, weird because titel is named "Evererspring", but it is really the Fibar Roller Shutter)
3. Fibar Group Dimmer (15.0) -> not working (Fibar Dimmer Switch)

Hope this iformation will help with the problem. 
btw: where can i find the "/accessories" from HomeBrige instance? is this useful too?

[devices.txt](https://github.com/SphtKr/homebridge-zway/files/121448/devices.txt)

**Comment by SphtKr** [comment] 2016-02-11 05:39
Hmm.

Everything here looks correct. Can you try something for me: the way homebridge-zway controls accessories is to call the URLs defined in the Z-Way server API. If those are working, then the problem is in my code. If they don't work, then there's some problem on the Z-Way side...or they have changed something in rc6.

Try this: after logging into the Z-Way web UI--like you did to get the `devices` file--in the same browser, hit this URL: 

    http://longsword.local:8083/ZAutomation/api/v1/devices/ZWayVDev_zway_3-0-37/command/on

or

    http://longsword.local:8083/ZAutomation/api/v1/devices/ZWayVDev_zway_3-0-37/command/off

Does that raise and lower your window shutters?

Or, do these:

    http://longsword.local:8083/ZAutomation/api/v1/devices/ZWayVDev_zway_15-0-38/command/on
    http://longsword.local:8083/ZAutomation/api/v1/devices/ZWayVDev_zway_15-0-38/command/off

Turn on and off the dimmer?

If those don't work, did you get any error text in the browser window? If they do work, let me know and I'll give you the next troubleshooting steps.

**Comment by devbox** [comment] 2016-02-11 17:32
Hi,
i tried the commands, and every command works. 
As i edited my post, now its working also with the home kit app and siri. :)
So, i have no idea, why it is working now. only think i have done again was a device interview for both devices.

**Comment by SphtKr** [comment] 2016-02-12 05:13
Hmm. Okay, we'll leave this open for a bit--in case it acts up again we can troubleshoot further. But good news!

**Comment by emilp333** [comment] 2016-02-28 17:46
It would be interesting to se your device list now after new Interview of your shutter to see if it has changed from a switchbinary to something else. Can you upload your device list again?

**Comment by Fingerz** [comment] 2016-04-17 17:49
I've got a similar issue after upgrading to 0.4.0 and ZWay 2.2.2. My dimmers don't have any controls (on/off or dimming), only switches (binary lights) work. Using the direct URL hit works (as described above). Any suggestions?

**Comment by SphtKr** [comment] 2016-04-18 04:59
@Fingerz Your problem is that you've upgraded to Z-Way 2.2.2. They changed one little field--`probeType`--in 2.2.2 but they changed it on a BUNCH of device types, if not all of them. 😡 Looks like it's time for me to upgrade and royally break myself just so I can see what all the heck they did.

**Comment by Fingerz** [comment] 2016-04-18 05:27
What version of ZWay should I roll back to until you’ve had time to implement a workaround? I was on 2.2.0 before…is 2.2.1 safe? Is their version roll back process reliable or am I hosed?

**Comment by Fingerz** [comment] 2016-04-19 04:06
Update: as expected rolling back to ZWay v2.2.1 has resolved the issues I was having.

**Comment by SphtKr** [comment] 2016-04-19 16:50
Great! Glad to hear it, but of course I do intend to support those changes in 2.2.2 soon. And the way I handle those, it should be backwards compatible so you won't have to switch to 2.2.2 immediately after I release 0.5.0.

**Comment by SphtKr** [comment] 2016-11-11 14:57
Closing as it appears this issue resolved and did not recur.

**Closed by SphtKr** 2016-11-11 14:57 UTC
